name: ZomZoneCore
version: '${project.version}'
main: net.monkeyfunky.devteam.core.Core
api-version: '1.16'
authors: [ eight_y_88 ]

description: ZomZone Core Plugin
website: https://monkeyfunky.net

depend:
  - "ZomZoneEconomy"
  - "ZomZoneStatus"

commands:
  reloadcore:
    permission: op
  debugcore:
    permission: op
  togive:
    permission: op